logging:
  level:
    root: INFO
    org.springframework.security: INFO

spring:
  mvc:
    favicon:

  datasource:
    url: jdbc:h2:tcp://localhost/~/DB/h2/data/spring-security-memo
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create