logging:
  level:
    root: INFO
    org.springframework.security: INFO

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/DB/h2/data/memo
    username: sa
    password:


  jpa:
    hibernate:
      ddl-auto: create


  security:
    user:
      name: user
      password: 1234